### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by victor95pc** [bazzel/ember-guides-to-epub#1]
Look like he is trying to find a file guide.yml, can someone helps?

**Comment by bazzel** [comment]
I think the ember site changed its structure since I last updated this repo. Sorry for that.

I have found a free epub version for the ember guides, not sure if these are the most recent, but you can try.

https://leanpub.com/emberjsguides

**Comment by victor95pc** [comment]
Actually is not your fault, Ember now use HTML instead markdown, maybe I can help you updating your script I don't know much how create epubs, but I can definitely help you with Ruby.
